### ISSUE TITLE
`mkdir <database>` throws exception for non admin user

### ISSUE THREAD

**Issue by artur-points** [kevinjqiu/cdbcli#30]
admin@localhost/> mkdir aaa
Traceback (most recent call last):
  File "/Users/artur.levchenko/dev/cdbcli/venv/bin/cdbcli", line 9, in <module>
    load_entry_point('cdbcli', 'console_scripts', 'cdbcli')()
  File "/Users/artur.levchenko/dev/cdbcli/venv/lib/python3.5/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/Users/artur.levchenko/dev/cdbcli/venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/artur.levchenko/dev/cdbcli/venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/Users/artur.levchenko/dev/cdbcli/venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(_args, *_kwargs)
  File "/Users/artur.levchenko/dev/cdbcli/cdbcli/main.py", line 61, in main
    r.run()
  File "/Users/artur.levchenko/dev/cdbcli/cdbcli/repl.py", line 102, in run
    self._run()
  File "/Users/artur.levchenko/dev/cdbcli/cdbcli/repl.py", line 88, in _run
    eval_(self._environment, self._couch_server, cmd_text)
  File "/Users/artur.levchenko/dev/cdbcli/cdbcli/repl.py", line 43, in eval_
    handler(environment=environment, couch_server=couch_server, variables=m.variables())
  File "/Users/artur.levchenko/dev/cdbcli/cdbcli/commands.py", line 24, in wrapper
    return fn(_args, *_kwargs)
  File "/Users/artur.levchenko/dev/cdbcli/cdbcli/commands.py", line 173, in mkdir
    couch_server.create(database_name)
  File "/Users/artur.levchenko/dev/cdbcli/venv/lib/python3.5/site-packages/couchdb/client.py", line 206, in create
    self.resource.put_json(name)
  File "/Users/artur.levchenko/dev/cdbcli/venv/lib/python3.5/site-packages/couchdb/http.py", line 549, in put_json
    *_params)
  File "/Users/artur.levchenko/dev/cdbcli/venv/lib/python3.5/site-packages/couchdb/http.py", line 564, in _request_json
    headers=headers, **params)
  File "/Users/artur.levchenko/dev/cdbcli/venv/lib/python3.5/site-packages/couchdb/http.py", line 560, in _request
    credentials=self.credentials)
  File "/Users/artur.levchenko/dev/cdbcli/venv/lib/python3.5/site-packages/couchdb/http.py", line 392, in request
    raise Unauthorized(error)
couchdb.http.Unauthorized: ('unauthorized', 'You are not a server admin.')

**Comment by kevinjqiu** [comment]
Maybe catch the exception and throw a better error message. I think for now we should just catch couchdb exceptions, and throw `RuntimeError(str(couchdb_err))`

**Comment by kevinjqiu** [comment]
Fixed in #35
